<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\CardPlayer.ico</ApplicationIcon>
	<Product>go fetch Card Player</Product>
	<ApplicationName>go fetch Card Player</ApplicationName>
	<AssemblyName>go fetch Card Player</AssemblyName>
	<Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="README.md" />
    <None Remove="Resources\CardPlayer.ico" />
    <None Remove="Resources\CardPlayer_title.svg" />
    <None Remove="Resources\CardPlayer_title.png" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\CardPlayer.ico" />
    <AvaloniaResource Include="Resources\CardPlayer_title.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\CardPlayer.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.9" />
  </ItemGroup>

  <ItemGroup>
    <None Update="MediaPaths.csv">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Programs.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="RemoteProfiles.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

